### ISSUE TITLE
DocumentClient scan not working?

### ISSUE THREAD

**Issue by pY4x3g** [agilord/aws_client#190]
Hi, I tried a simple scan with the new DocumentClient library and I get the following error:

```dart
Unhandled exception:
NoSuchMethodError: The method 'map' was called on null.
Receiver: null
Tried calling: map<String, AttributeValue>(Closure: (String, dynamic) => MapEntry<String, AttributeValue>)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      DynamicTranslator.fromJsonToAttributeValue (package:document_client/src/translator.dart:61:7)
#2      DocumentClient.scan (package:document_client/document_client.dart:353:44)
```
command I issued
```dart
  final dynamodb = DocumentClient(region: region);
  var scan = await dynamodb.scan(
      tableName: "tableName");
```

**Comment by Schwusch** [comment]
There's a [new release](https://pub.dev/packages/document_client#-changelog-tab-) with a fix, thanks for reporting!

**Comment by pY4x3g** [comment]
thanks for the fix!
