### ISSUE TITLE
Unhandled Exception: NoSuchMethodError: The getter 'keys' was called on null.

### ISSUE THREAD

**Issue by bjoffficial** [agilord/aws_client#239]
<h2>Key was called on NULL</h2>
I created the new project and I used this aws_kinesisvideo_api package to send the live video broadcast to AWS but I'm getting this error while using this package. I couldn't find any clear documents about how to parse the parameters for KinesisVideo() constructor and even if I pass all the parameters I'm still getting this error. can anyone please help me to find the solution on this

<h3>pubspec.yaml</h3>

```
dependencies:
  flutter:
    sdk: flutter
  aws_kinesisvideo_api: ^0.0.2
  camera: ^0.5.8+5
```

<h3>CameraPage.dart</h3>

```
class CameraPage extends StatefulWidget {
  @override
  _CameraPageState createState() => _CameraPageState();
}

class _CameraPageState extends State<CameraPage> {

  CameraController controller;
  var index=0;
  final service = KinesisVideo(region: 'ap-south-1',credentials: AwsClientCredentials
    (accessKey: "XXXXXXXXXXXXXXXXXXXXXX",
    secretKey: "XXXXXXXXXXXXXXXXXXXXXX",),);

  @override
  void initState() {
    controller = CameraController(cameras[index], ResolutionPreset.medium);
    controller.initialize().then((_) {
      if (!mounted) {
        return;
      }
      setState(() {});
    });
    super.initState();
  }
  @override
  Widget build(BuildContext context) {
    final mediaQuery=MediaQuery.of(context).size;
    if (!controller.value.isInitialized) {
      return Container();
    }
    return Scaffold(
      body: Container(
        width: mediaQuery.width,
        height: mediaQuery.height*0.9,
        child: Stack(
          children: [
            CameraPreview(controller),
            Positioned(bottom: 20,
            child: Container(
              width: mediaQuery.width,
              child: Row(
                children: [
                  Spacer(),
                  Container(width: 40.0,),
                  Spacer(),
                  InkWell(
                    onTap: (){
                      service.createStream(streamName: "demo_stream",
                          );
                    },
                    child: Container(
                      width: 100.0,
                      height: 100.0,
                      decoration: BoxDecoration(
                        color: Colors.red,
                        shape: BoxShape.circle,
                      ),
                      child: Center(
                        child: Text('Emergency',style: TextStyle(color: Colors.white),),
                      ),
                    ),
                  ),
                  Spacer(),
                  IconButton(icon: Icon(Icons.switch_camera,size: 40.0,color: Colors.white,),onPressed: (){
                    setState(() {
                      if(index==0){
                        index=1;
                      }else{
                        index=0;
                      }
                      controller = CameraController(cameras[index], ResolutionPreset.high);
                      controller.initialize().then((_) {
                        if (!mounted) {
                          return;
                        }
                        setState(() {});
                      });
                    });
                  },),
                  Spacer(),
                ],
              ),
            ),),
          ],
        ),
      ),
    );
  }
}
```

<h2> The error message </h2>

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The getter 'keys' was called on null.
E/flutter ( 7820): Receiver: null
E/flutter ( 7820): Tried calling: keys
E/flutter ( 7820): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter ( 7820): #1      MapMixin.addAll (dart:collection/maps.dart:128:25)
E/flutter ( 7820): #2      RestJsonProtocol.send (package:shared_aws_api/src/protocol/rest-json.dart:55:16)
E/flutter ( 7820): #3      KinesisVideo.createStream (package:aws_kinesisvideo_api/kinesisvideo-2017-09-30.dart:242:38)
E/flutter ( 7820): #4      _CameraPageState.build.<anonymous closure> (package:testing_kinesis/main.dart:130:38)
E/flutter ( 7820): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:953:19)
E/flutter ( 7820): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1059:38)
E/flutter ( 7820): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 7820): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:522:11)
E/flutter ( 7820): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter ( 7820): #10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
E/flutter ( 7820): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
E/flutter ( 7820): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter ( 7820): #13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter ( 7820): #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter ( 7820): #15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter ( 7820): #16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter ( 7820): #17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter ( 7820): #18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 7820): #19     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 7820): #20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 7820): #21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 7820): #22     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter ( 7820): #23     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 7820): #24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 7820): #25     _invoke1 (dart:ui/hooks.dart:281:10)
E/flutter ( 7820): #26     _dispatchPointerDataPacket (dart:ui/hooks.dart:190:5)
```

I'm not sure what is right and wrong here so can anyone provides the clear documents for this aws_kinesisvideo_api and the demo code snippet for making this app send the video stream data to AWS

**Comment by Schwusch** [comment]
Thanks for the exemplary bug report! It is a joy to debug when it is detailed like that.

This is a bug in the `shared_aws_api` library, where `RestJsonProtocol.send()` didn't account for headers being null in some cases. In this case, `KinesisVideo.createStream()` do not provide header arguments, since there is none in the specification.
This then fails:
```dart
final rq = Request(...);
rq.headers.addAll(headers); // headers is null
```
This is one of those misses that will be a compile errors when Dart gets null-safety :tada:
I'll make a PR and ask @isoos to make a patch release. After the patch fix, it should work after running `pub upgrade` in your project.

Thanks again for the bug report!

**Comment by isoos** [comment]
published, thanks for the report and the fix!
